name: build
on: 
  push:
    branches:
      - master
    tags:
    - '!*' # Do not execute on tags
    paths:
    - source/*
    - test/*
    - '*.json'
    - package.lock
    - .github/workflows/*
  pull_request:

jobs:
    build:
        name: Node.js ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 14
                    - 16
                    - 18
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
    coverage:
        name: coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                node-version: '16'
            - run: npm install
            - run: npm run test
            - uses: paambaati/codeclimate-action@v3.2.0
              env:
                CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              if: env.CC_TEST_REPORTER_ID != null
              with:
                coverageCommand: yarn test
                debug: true
